### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by voxik** [rails/rails-deprecated_sanitizer#5]
I'd appreciate if you can add license file into the gem. This would be helpful to get this package into Fedora [1].

[1] https://fedoraproject.org/wiki/Packaging:LicensingGuidelines#License_Text

**Comment by rafaelfranca** [comment]
Is this file not sufficient? https://github.com/rails/rails-deprecated_sanitizer/blob/master/LICENSE.txt

**Comment by voxik** [comment]
It is sufficient. Unfortunately it is not included in the .gem file.

**Comment by rafaelfranca** [comment]
Right. Now I got your request. We just need to rename the file.

**Comment by voxik** [comment]
Thx. Sorry for not being clear
